# Generated by Django 3.2.10 on 2022-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0)),
                ('item', models.ManyToManyField(to='stripe_api.Item')),
            ],
        ),
    ]
