# Generated by Django 3.2.10 on 2022-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('ru', 'RUB'), ('us', 'USD')], default='ru', max_length=2),
        ),
    ]
